on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: JQPW4H4NO7IJWH4R6OHAICZ3X2UV3ZKKK36GD33FHS2FHMNWW2RDO7IY
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
